LOCAL_PATH := vendor/google/now
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/system/lib/libgoogle_hotword_jni.so:system/lib/libgoogle_hotword_jni.so \
    $(LOCAL_PATH)/system/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so \
    $(LOCAL_PATH)/system/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so \
    $(LOCAL_PATH)/system/usr/srec/en-US/hclg_shotword:system/usr/srec/en-US/hclg_shotword \
    $(LOCAL_PATH)/system/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf \
    $(LOCAL_PATH)/system/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst \
    $(LOCAL_PATH)/system/usr/srec/en-US/wordlist:system/usr/srec/en-US/wordlist \
    $(LOCAL_PATH)/system/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config \
    $(LOCAL_PATH)/system/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config \
    $(LOCAL_PATH)/system/usr/srec/en-US/commands.abnf:system/usr/srec/en-US/commands.abnf \
    $(LOCAL_PATH)/system/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols \
    $(LOCAL_PATH)/system/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config \
    $(LOCAL_PATH)/system/usr/srec/en-US/clg:system/usr/srec/en-US/clg \
    $(LOCAL_PATH)/system/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist \
    $(LOCAL_PATH)/system/usr/srec/en-US/hotword_classifier:system/usr/srec/en-US/hotword_classifier \
    $(LOCAL_PATH)/system/usr/srec/en-US/hotword_prompt.txt:system/usr/srec/en-US/hotword_prompt.txt \
    $(LOCAL_PATH)/system/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config \
    $(LOCAL_PATH)/system/usr/srec/en-US/hotword.config:system/usr/srec/en-US/hotword.config \
    $(LOCAL_PATH)/system/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist \
    $(LOCAL_PATH)/system/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm \
    $(LOCAL_PATH)/system/usr/srec/en-US/phone_state_map:system/usr/srec/en-US/phone_state_map \
    $(LOCAL_PATH)/system/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config \
    $(LOCAL_PATH)/system/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn \
    $(LOCAL_PATH)/system/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer \
    $(LOCAL_PATH)/system/usr/srec/en-US/hotword_normalizer:system/usr/srec/en-US/hotword_normalizer \
    $(LOCAL_PATH)/system/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model \
    $(LOCAL_PATH)/system/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst \
    $(LOCAL_PATH)/system/usr/srec/en-US/hotword_word_symbols:system/usr/srec/en-US/hotword_word_symbols \
    $(LOCAL_PATH)/system/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata \
    $(LOCAL_PATH)/system/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst \
    $(LOCAL_PATH)/system/usr/srec/en-US/dict:system/usr/srec/en-US/dict \
    $(LOCAL_PATH)/system/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer \
    $(LOCAL_PATH)/system/priv-app/GoogleSearch.apk:system/priv-app/GoogleSearch.apk \
    $(LOCAL_PATH)/system/addon.d/72-gapps-now.sh:system/addon.d/72-gapps-now.sh \
