LOCAL_PATH := vendor/google/core
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/system/app/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter.apk \
    $(LOCAL_PATH)/system/lib/libjgcastservice.so:system/lib/libjgcastservice.so \
    $(LOCAL_PATH)/system/lib/libocrclient.so:system/lib/libocrclient.so \
    $(LOCAL_PATH)/system/lib/libgcastv2_base.so:system/lib/libgcastv2_base.so \
    $(LOCAL_PATH)/system/lib/libjni_latinime.so:system/lib/libjni_latinime.so \
    $(LOCAL_PATH)/system/lib/libconscrypt_gmscore_jni.so:system/lib/libconscrypt_gmscore_jni.so \
    $(LOCAL_PATH)/system/lib/libgcastv2_support.so:system/lib/libgcastv2_support.so \
    $(LOCAL_PATH)/system/lib/libAppDataSearch.so:system/lib/libAppDataSearch.so \
    $(LOCAL_PATH)/system/lib/libgames_rtmp_jni.so:system/lib/libgames_rtmp_jni.so \
    $(LOCAL_PATH)/system/lib/libgmscore.so:system/lib/libgmscore.so \
    $(LOCAL_PATH)/system/etc/permissions/features.xml:system/etc/permissions/features.xml \
    $(LOCAL_PATH)/system/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    $(LOCAL_PATH)/system/etc/permissions/com.google.android.ble.xml:system/etc/permissions/com.google.android.ble.xml \
    $(LOCAL_PATH)/system/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    $(LOCAL_PATH)/system/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    $(LOCAL_PATH)/system/etc/permissions/com.google.android.camera2.xml:system/etc/permissions/com.google.android.camera2.xml \
    $(LOCAL_PATH)/system/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml \
    $(LOCAL_PATH)/system/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    $(LOCAL_PATH)/system/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    $(LOCAL_PATH)/system/framework/com.google.android.ble.jar:system/framework/com.google.android.ble.jar \
    $(LOCAL_PATH)/system/framework/com.google.android.camera2.jar:system/framework/com.google.android.camera2.jar \
    $(LOCAL_PATH)/system/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    $(LOCAL_PATH)/system/priv-app/GoogleServicesFramework.apk:system/priv-app/GoogleServicesFramework.apk \
    $(LOCAL_PATH)/system/priv-app/PrebuiltGmsCore.apk:system/priv-app/PrebuiltGmsCore.apk \
    $(LOCAL_PATH)/system/priv-app/GoogleLoginService.apk:system/priv-app/GoogleLoginService.apk \
    $(LOCAL_PATH)/system/priv-app/GoogleFeedback.apk:system/priv-app/GoogleFeedback.apk \
    $(LOCAL_PATH)/system/priv-app/GoogleBackupTransport.apk:system/priv-app/GoogleBackupTransport.apk \
    $(LOCAL_PATH)/system/priv-app/Phonesky.apk:system/priv-app/Phonesky.apk \
    $(LOCAL_PATH)/system/priv-app/GooglePartnerSetup.apk:system/priv-app/GooglePartnerSetup.apk \
    $(LOCAL_PATH)/system/priv-app/SetupWizard.apk:system/priv-app/SetupWizard.apk \
    $(LOCAL_PATH)/system/priv-app/GoogleOneTimeInitializer.apk:system/priv-app/GoogleOneTimeInitializer.apk \
    $(LOCAL_PATH)/system/addon.d/70-gapps.sh:system/addon.d/70-gapps.sh \
